#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 25 17:37:51 2023

@author: wrichter

Configuration data and filters for CPUs.
"""

amdRename = {'Model': 'hw_model', 'Unnamed: 0': 'processor_id',
             'Line': 'hw_model.spec_int2k6', 'L1 Cache': 'l1_cache',
             'L2 Cache': 'l2_cache', 'L3 Cache': 'l3_cache', 'Launch Date': 'date',
             'Family': 'test_sponsor.spec_int2k6', 'Total Cores': 'hw_ncores', 'Total Threads': 'hw_threads',
             '# of CPU Cores': 'hw_ncores', 'Memory Channels': 'memory channels',
             '# of Threads': 'hw_nthreadspercore', 'Graphics Core Count': 'hw_gcores',
             'Base Clock': 'clock', 'Max. Boost Clock ¹ ²': 'max_clock', 'System Memory Type': 'memory types',
             'Default TDP': 'tdp', 'AMD Configurable TDP (cTDP)': 'ctdp', '*OS Support': 'os Support'}
amdDrop = ['Thermal Solution PIB', 'Recommended Cooler', 'Thermal Solution MPK',
           'PCI Express® Version', 'CPU Socket', 'Socket Count', '1kU Pricing',
           'Unlocked for Overclocking', 'All Core Boost Speed', 'Unnamed: 1',
           'Product ID Tray', 'Product ID Boxed', 'Product ID MPK']

intelRename = {'Product Collection': 'hw_model', 'Processor Number': 'test_sponsor.spec_int2k6',
               'Processor Graphics ‡': 'graphics_model', 'System Memory Type': 'System Memory Specification',
               'TDP': 'tdp', 'Configurable TDP-down': 'ctdp', 'Launch Date': 'date', 'Cache': 'l2_cache',
               'Memory Types': 'memory types', 'Max # of Memory Channels': 'memory_channels',
               'Vertical Segment': 'Platform', 'Processor Base Frequency': 'clock',
               'Intel® Turbo Boost Technology 2.0 Frequency‡': 'max_clock', 'Graphics Name‡': 'graphics_mode',
               'Total Cores': 'hw_ncores', 'Total Threads': 'total_threads',
               '# of Performance-cores': 'performance_cores', '# of Efficiency-cores': 'Efficiency-cores',
               'Platform': 'platform', '# of Displays Supported‡': 'max_displays',
               'Intel® Turbo Boost Max Technology 3.0 Frequency ‡': 'turbo_boost_clock',
               'Graphics Base Frequency': 'graphics_base', 'Graphics Max Dynamic Frequency': 'graphics_max',
               'Graphics Output': 'graphics_out'}
intelDrop = ['Recommended Customer Price', 'Essentials', 'nan', 'Use Conditions', 'Marketing Status',
             'Servicing Status', 'End of Servicing Updates Date', 'Embedded Options Available',
             '4K Support', 'Max Resolution (HDMI)‡', '# of QPI Links', 'Graphics Base Clock'
                                                                       'Max Resolution (DP)‡',
             'Max Resolution (eDP - Integrated Flat Panel)‡', 'Baseband Functions',
             'RF Transceiver', 'RF Transceiver Functions', 'Protocol Stack', 'Intel® Smart Idle Technology',
             'DirectX* Support', 'OpenGL* Support', 'Intel® Quick Sync Video', 'Max Refresh Rate',
             'Intel® InTru™ 3D Technology', 'Intel® Clear Video HD Technology',
             'Intel® Clear Video Technology', '# of Displays Supported ‡', 'Thermal Solution Specification',
             'Package Size', 'TJUNCTION', 'Intel® Turbo Boost Technology ‡', 'Intel® Hyper-Threading Technology ‡',
             'Intel® Transactional Synchronization Extensions', 'Intel® 64 ‡', 'Instruction Set',
             'Instruction Set Extensions', 'Idle States', 'Enhanced Intel SpeedStep® Technology',
             'Thermal Monitoring Technologies', 'Intel® Identity Protection Technology ‡',
             'Intel® My WiFi Technology', 'Intel® Flex Memory Access', 'Intel® Smart Response Technology',
             'Intel® Speed Shift Technology', 'Intel vPro® Eligibility ‡', 'Intel® AES New Instructions',
             'Secure Key', 'Intel® Software Guard Extensions (Intel® SGX)', 'Graphics Base Clock', 'PCI Support',
             'Intel® Memory Protection Extensions (Intel® MPX)', 'Intel® OS Guard', 'Supported FSBs',
             'Performance-core Max Turbo Frequency', 'Efficient-core Max Turbo Frequency', '# of Efficient-cores',
             'Intel® Trusted Execution Technology ‡', 'Execute Disable Bit ‡', 'Macrovision* License Required',
             'Interfaces Supported', 'End of Interactive Support Date', 'Additional Information',
             'Maximum High Bandwidth Memory (HBM)†', 'Integrated Intel® Omni-Path Architecture (Intel® OPA)',
             'Max Resolution (VGA)‡', 'Integrated Wireless‡', '4G WiMAX Wireless Technology',
             'Intel® Boot Guard', 'Intel® Stable IT Platform Program (SIPP)', 'Intel® Quick Resume Technology',
             'Intel® Quiet System Technology', 'Intel® AC97 Technology', 'Intel® I/O Acceleration Technology',
             'ECC Memory Supported ‡', 'FSB Parity', 'Expected Discontinuance', 'Processing Die Size',
             'Intel® Virtualization Technology (VT-x) ‡', 'ECC Memory Supported   ‡',
             'Intel® Virtualization Technology for Directed I/O (VT-d) ‡', 'OpenCL* Support',
             'Multi-Format Codec Engines', 'Intel® VT-x with Extended Page Tables (EPT) ‡', 'Scalability',
             'PCI Express Revision', 'PCI Express Configurations ‡', 'Intel® Turbo Boost Max Technology 3.0 ‡',
             'Max # of PCI Express Lanes', 'Configurable TDP-up Frequency', 'Configurable TDP-up',
             'Configurable TDP-down Frequency', 'Intel® Stable Image Platform Program (SIPP)',
             'Intel® Threat Detection Technology (TDT)', 'Intel® Active Management Technology (AMT) ‡',
             'Intel® Standard Manageability (ISM) ‡', 'Intel® One-Click Recovery ‡',
             'Intel® Hardware Shield Eligibility ‡', 'Intel® Control-Flow Enforcement Technology',
             'Intel® Total Memory Encryption - Multi Key', 'Intel® Total Memory Encryption',
             'Mode-based Execute Control (MBE)', 'Intel® QuickAssist Software Acceleration',
             'Intel® Virtualization Technology with Redirect Protection (VT-rp) ‡',
             'Intel® On Demand Activation Model', 'Intel® Data Streaming Accelerator (DSA)',
             'Intel® Advanced Matrix Extensions (AMX)', 'Intel® QuickAssist Technology (QAT)',
             'Intel® Dynamic Load Balancer (DLB)', 'Graphics Burst Frequency', 'Warranty Period',
             'Intel® Thermal Velocity Boost Temperature', 'Intel® Adaptive Boost Technology', 'Burst Frequency',
             'Intel® Optane™ DC Persistent Memory Supported', 'Package Carrier', 'DTS Max',
             'Intel® In-memory Analytics Accelerator (IAA)', 'Intel® vRAN Boost', 'Maximum Turbo Power',
             'Default Maximum Enclave Page Cache (EPC) Size for Intel® SGX', 'Intel® Crypto Acceleration',
             'Intel® Platform Firmware Resilience Support', 'Maximum Enclave Size Support for Intel® SGX',
             'Intel® Speed Select Technology', 'Additional Information URL', 'Intel® UPI Speed',
             'Intel® Instruction Replay Technology', 'VID Voltage Range', 'Intel SpeedStep® Max Frequency',
             'Intel® Remote Platform Erase (RPE) ‡', 'Vulkan*  Support', 'H.264 Hardware Encode/Decode',
             'H.265 (HEVC) Hardware Encode/Decode', 'MIPI SoundWire*', 'Intel® Adaptix™ Technology',
             'Intel® Optane™ Memory Supported ‡', 'Intel® TSX-NI', '# of AVX-512 FMA Units',
             'Intel® Volume Management Device (VMD)', 'Intel® Time Coordinated Computing (Intel® TCC)‡',
             'Intel® Gaussian & Neural Accelerator', 'Intel® Thread Director', 'Maximum Assured Frequency',
             'Intel® Deep Learning Boost (Intel® DL Boost)', 'Intel® Image Processing Unit',
             'Intel® Smart Sound Technology', 'Intel® Wake on Voice', 'Intel® High Definition Audio',
             'Intel® Thermal Velocity Boost', 'Secure Boot', 'Operating Temperature (Maximum)',
             'Operating Temperature (Minimum)', 'TCASE', 'Direct Media Interface (DMI) Revision',
             'Intel® Thunderbolt™ 4', 'Microprocessor PCIe Revision', 'Max # of DMI Lanes',
             'Chipset / PCH PCIe Revision', 'Included Items', 'Product Brief', 'Description',
             'Functional Safety (FuSa) Documentation Available', 'Minimum Assured Power',
             'Intel® Thermal Velocity Boost Frequency', 'Minimum Assured Frequency', 'Maximum Assured Power', ]

